In [18]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing  import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [25]:
iris_data = load_iris()

In [43]:
# Convert to a DataFrame for better visualization
iris_df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
#iris_df['target'] = iris_data.target

# Display the first few rows of the dataset
print(iris_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [30]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [27]:
print("Example data: ")
print(iris_data.data[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [28]:
print("Example labels: ", iris_data.target_names)
print(iris_data.target[:5])

Example labels:  ['setosa' 'versicolor' 'virginica']
[0 0 0 0 0]


In [31]:
x =iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

In [49]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y_)
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [50]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [51]:
# build a model
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu', name="fc1"))
model.add(Dense(10, activation='relu', name="fc2"))
model.add(Dense(3, activation='softmax', name="output"))

print("Neural Network Model Summary: ")
print(model.summary())



Neural Network Model Summary: 


/home/vscode/.local/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ fc1 (Dense)                     │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc2 (Dense)                     │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [52]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data
results = model.evaluate(test_x, test_y)
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Epoch 1/200


24/24 - 1s - 30ms/step - accuracy: 0.2250 - loss: 1.1698
Epoch 2/200
24/24 - 0s - 3ms/step - accuracy: 0.3833 - loss: 1.0731
Epoch 3/200
24/24 - 0s - 3ms/step - accuracy: 0.4250 - loss: 0.9981
Epoch 4/200
24/24 - 0s - 2ms/step - accuracy: 0.7083 - loss: 0.9026
Epoch 5/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.8286
Epoch 6/200
24/24 - 0s - 2ms/step - accuracy: 0.8417 - loss: 0.7564
Epoch 7/200
24/24 - 0s - 2ms/step - accuracy: 0.8917 - loss: 0.6998
Epoch 8/200
24/24 - 0s - 2ms/step - accuracy: 0.9000 - loss: 0.6479
Epoch 9/200
24/24 - 0s - 2ms/step - accuracy: 0.8583 - loss: 0.6022
Epoch 10/200
24/24 - 0s - 2ms/step - accuracy: 0.9000 - loss: 0.5587
Epoch 11/200
24/24 - 0s - 2ms/step - accuracy: 0.9083 - loss: 0.5176
Epoch 12/200
24/24 - 0s - 2ms/step - accuracy: 0.9333 - loss: 0.4803
Epoch 13/200
24/24 - 0s - 2ms/step - accuracy: 0.9000 - loss: 0.4520
Epoch 14/200
24/24 - 0s - 2ms/step - accuracy: 0.9333 - loss: 0.4185
Epoch 15/200
24/24 - 0s - 2ms/step - accuracy: 0.9750 

In [55]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=500)

# Test on unseen data
results = model.evaluate(test_x, test_y)
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Epoch 1/500
24/24 - 1s - 28ms/step - accuracy: 0.9583 - loss: 0.0817
Epoch 2/500
24/24 - 0s - 3ms/step - accuracy: 0.9750 - loss: 0.0478
Epoch 3/500
24/24 - 0s - 3ms/step - accuracy: 0.9917 - loss: 0.0379
Epoch 4/500
24/24 - 0s - 3ms/step - accuracy: 0.9917 - loss: 0.0360
Epoch 5/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0344
Epoch 6/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0339
Epoch 7/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0347
Epoch 8/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0365
Epoch 9/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0348
Epoch 10/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0313
Epoch 11/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0303
Epoch 12/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0317
Epoch 13/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0314
Epoch 14/500
24/24 - 0s - 2ms/step - accuracy: 0.9917 - loss: 0.0310
Epoch 15/500
24/24 - 0s - 2ms/step - accur

In [57]:
for i in range(len(test_x)):
    prediction = np.argmax(model.predict(test_x[i].reshape(1, 4)))
    print("Predicted: {}, Actual: {}".format(prediction, np.argmax(test_y[i])))

NameError: name 'np' is not defined